baseURL = 'https://ZHLOVEYY.github.io/'  
languageCode = 'en-us'
title = "HarryMonkeyEXE's Game Center"
theme = 'PaperMod'  # 替换为你的主题名

[params]
  description = 'Deep dives into Godot engine, game art, and music composition.'
  author = 'Carlos'
  images = ['cover.jpg']  # 上传封面图到 static/

[taxonomies]
  category = 'categories'
  tag = 'tags'

[menu]
  [[menu.main]]
    identifier = 'all'
    name = 'ALL'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'godot'
    name = 'Godot'
    url = '/categories/godot/'
    weight = 20
  [[menu.main]]
    identifier = 'painting'
    name = 'Painting'
    url = '/categories/painting/'
    weight = 25
  [[menu.main]]
    identifier = 'music'
    name = 'Music'
    url = '/categories/music/'
    weight = 30
  [[menu.main]]
    identifier = 'IT'
    name = 'IT'
    url = '/categories/IT/'
    weight = 35
  [[menu.main]]
    identifier = 'collection'
    name = 'Collection of Works'
    url = '/categories/collection-of-works/'
    weight = 40

  [caches]
  [caches.images]
    dir = ':cacheDir/images'